{{- if .Values.console.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: console-env
  namespace: {{ .Release.Namespace }}
  labels: {{- include "minio-operator.console-labels-common" . | nindent 4 }}
data:
  CONSOLE_PORT: "9090"
  CONSOLE_TLS_PORT: "9443"
{{- end }}
